pyvips/base.py
pyvips/gvalue.py
pyvips/tests/helpers.py
pyvips/tests/test_arithmetic.py
pyvips/tests/test_colour.py
pyvips/tests/test_conversion.py
pyvips/tests/test_convolution.py
pyvips/tests/test_create.py
pyvips/tests/test_draw.py
pyvips/tests/test_foreign.py
pyvips/tests/test_gvalue.py
pyvips/tests/test_histogram.py
pyvips/tests/test_iofuncs.py
pyvips/tests/test_morphology.py
pyvips/tests/test_resample.py
pyvips/vimage.py
pyvips/vinterpolate.py
pyvips/vobject.py
pyvips/voperation.py

Python 2.7.5:
```bash
nosetests --logging-level=WARNING
..............................................................................................................................................................................................
----------------------------------------------------------------------
Ran 190 tests in 38.668s
OK
memory: high-water mark 126.94 MB
````
Python 3.6.2:
```bash
python3.6 -m "nose" --logging-level=WARNING
..............................................................................................................................................................................................
----------------------------------------------------------------------
Ran 190 tests in 38.750s
OK
memory: high-water mark 126.94 MB
````

Python 3 support

---

pyvips/gvalue.py
pyvips/vimage.py
pyvips/vobject.py

This will fix the "maximum recursion depth exceeded" error when running the test suite (`nosetests`) without setting the logging level to warning (`--logging-level=WARNING`).
`VipsObject.get` was calling [`Image.__repr__`](https://github.com/jcupitt/pyvips/blob/cead977bad1e95f680c0f3c3ab0b9099c4738ca6/pyvips/vimage.py#L727-L730), which in turn was calling `VipsObject.get`. 😅

Fix debug logging

---

.gitignore
.travis.yml
setup.py
tox.ini

Tox and tox-travis are a good way to help a developer replicating the tests locally.
The sphinx-build could have a `-W` to be nit-picky but it breaks the build. And tox could run `flake8` as well but it would also break.
My goal was to remove `nose` since it an abandonware, but it felt like some kind of cleanup could help first.
Cheers,

Using Tox for testing

---

examples/read_profile.py
pyvips/voperation.py
setup.cfg
setup.py
tests/conftest.py
tests/helpers/helpers.py
tests/test_arithmetic.py
tests/test_colour.py
tests/test_conversion.py
tests/test_convolution.py
tests/test_create.py
tests/test_draw.py
tests/test_foreign.py
tests/test_gvalue.py
tests/test_histogram.py
tests/test_iofuncs.py
tests/test_morphology.py
tests/test_resample.py

Commits https://github.com/jcupitt/pyvips/commit/7e71ad9a7c784cc06fbad9b1b22f716261e30631, https://github.com/jcupitt/pyvips/commit/6cc99306765014f9fda55053424ff02161961f2a, https://github.com/jcupitt/pyvips/commit/87bf68a07c99a61dacdc5fea51e9c9dfa971652e and https://github.com/jcupitt/pyvips/commit/4180085e3bf6d0dd1f28233d4ac62198ebeb9814 were found when I worked on the unit tests of [net-vips](https://github.com/kleisauke/net-vips).
The last 2 commits (https://github.com/jcupitt/pyvips/commit/85975bf65a995e3943b96e9f09761f70cd838578 and https://github.com/jcupitt/pyvips/commit/f954246d2feef231cbd5025c3a7b30faacbf4557) were made because I had some spare time left today. :smile:

Convert unit tests from unittest to pytest + general cleanup

---

.travis.yml

* Update setuptools to work with python 3.7 (nightly)
* Update packages during pip install to fix weird dependency problems
* Remove fixed builds (except python-nightly) from allowed failures

Fix broken Travis CI builds

---

pyvips/error.py

This fixes UnicodeDecodeError exceptions on Python 2.7 if the blurb or description containts UTF-8 codepoints thate are missing in US-ASCII.
Fixes #45.

Fix Python 2.7 UnicodeDecodeError in _to_string

---

pyvips/enums.py
pyvips/vinterpolate.py
pyvips/vregion.py

Log messages from the native VIPS library were being logged via the `pyvips.vinterpolate` logger instead of `pyvips`. This was due to `pyvips/__init__.py` importing `*` from `pyvips.vinterpolate`, which has a `logger` property, resulting in `pyvips.logger` being replaced with `pyvips.vinterpolate.logger`.
This fixes that by adding `__all__` to all the modules being glob imported into `pyvips/__init__.py`.
e.g:
```
$ python
Python 3.7.4 (default, Sep 24 2019, 14:47:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging; logging.basicConfig(level=logging.WARN)
>>> import pyvips
>>> img = pyvips.Image.new_from_array([0])
>>> img.jpegsave_buffer(overshoot_deringing=True)
WARNING:pyvips.vinterpolate:VIPS: ignoring overshoot_deringing …
```

Fix glib VIPS logs going to pyvips.vinterpolate

---

pyvips/__init__.py
pyvips/voperation.py

This allows the libvips generators (`cplusplus/gen-operators.py` and `doc/gen-function-list.py`) to use the new Introspect class.

Move Introspect class to the public API

---

tests/test_progress.py

There is a small typo in tests/test_progress.py.
Should read `requires` rather than `reques`.

docs: Fix simple typo, reques -> requires

---

.travis.yml
README.rst
pyvips/vsourcecustom.py

Docs now mention libvips v8.9 is required for all features to work correctly. Closes https://github.com/libvips/pyvips/issues/218

Update docs for `SourceCustom`

---

pyvips/voperation.py

This PR fixes a small memory leak when `vips_cache_operation_build` fails. This can can be reproduced with:
```bash
VIPS_LEAK=1 python3 -c "import pyvips; pyvips.Image.new_from_buffer(b'GIF89a', '')"
```
(requires libvips to be configured with giflib)
Other FFI-based bindings probably need something similar as well. I also reordered the unsupported optional argument check to avoid a `KeyError`. For example, I now see:
```bash
$ python3 -c "import pyvips; pyvips.Operation.call('black', 10, 10, banana=42)"
pyvips.error.Error: black does not support optional argument banana
```
Instead of:
```bash
$ python3 -c "import pyvips; pyvips.Operation.call('black', 10, 10, banana=42)"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File …
```

Unref all assigned output objects prior raising an exception

---

pyvips/voperation.py

When a deprecated argument is used, an exception was being thrown because a format string was being used but the logger was expecting percent placeholders.  The current code would throw an exception.
For example:
```
Traceback (most recent call last):
File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
msg = self.format(record)
File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
return fmt.format(record)
File "/home/ubuntu/misc/girder_worker/env/lib/python3.6/site-packages/celery/utils/log.py", line 153, in format
msg = logging.Formatter.format(self, record)
File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
record.message = record.getMessage()
File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
msg = msg % self.args …
```

Fix logging deprecated arguments.

---

CHANGELOG.rst
pyvips/enums.py
pyvips/vimage.py

In parallel with libvips/libvips#2508

add hyperbolic functions

---

pyvips/base.py
pyvips/vdecls.py

Similar to #47, but for flags (e.g. `VipsForeignPngFilter`). Perhaps not very useful since that is the only flag/bitfield available in the public API of libvips (context: https://github.com/kleisauke/net-vips/pull/106).
I currently use this for wasm-vips here:
https://github.com/kleisauke/wasm-vips/blob/fafd4113090cf6b319d31d7db1f43f41f9b16f16/build/gen_type_declarations.py#L278
and:
https://github.com/kleisauke/wasm-vips/blob/fafd4113090cf6b319d31d7db1f43f41f9b16f16/build/gen_cpp_binding.py#L260

Add flags helper

---

CHANGELOG.rst
pyvips/vimage.py
tests/test_image.py

In the process of developing the fancy slicing code, I encountered a segfault that I now see was caused by trying `im.bandjoin([])`.  This tiny PR fixes that by making `im.bandjoin([])` an identity operation, adds a test, and adds an entry to the CHANGELOG.  Fixes #311.

fix im.bandjoin([]) segfault

---

CHANGELOG.rst
pyvips/vimage.py
tests/test_image.py

Hi John,
In my work I often find myself switching back and forth between the numpy, pandas, pytorch, and JAX world and the pyvips world.  Those other libraries support numpy's extended indexing syntax, in which you can either use a list of ints to extract (possibly duplicate) targeted subsets of indices or a list of bools (so-called boolean indexing or boolean slicing) to indicate which indices to retain.  In a common use-case for me, when working with many-band reflectance imaging spectroscopy or MA-XRF images, it's frequently desirable to pull out specific bands by wavelength to make a false-color image or to select bands from several many-band images according to some single band-wise criterion.  Extended indexing with a list of ints and with a list of bools makes these two use cases …

add numpy-style extended indexing, many new tests

---

CHANGELOG.rst
pyvips/vimage.py

__getattr__ is supposed to raise AttributeError for missing methods, and
do it at the time of call, not later. This should help eg. numpy array
integration.
See https://github.com/libvips/pyvips/issues/314

early detection of missing methods

---

CHANGELOG.rst
pyvips/vdecls.py
pyvips/vimage.py
tests/test_image.py

useful if you're modifying image memory arrays outside libvips, eg. with
numpy
see https://github.com/libvips/pyvips/pull/316

add invalidate() method

---

CHANGELOG.rst
pyvips/error.py
tests/helpers/helpers.py
tests/test_saveload.py

As discussed in #313, this PR enables `pathlib.Path` objects as filenames in Python 3.   There was already an `isinstance` call in the `_to_bytes` function, so this shouldn't really affect performance.  I also added a couple of simple tests.

accept pathlib.Path as filename (with tests)

---

pyvips/vimage.py
tests/test_image.py

Thanks for alerting me to the test failures with the new array functionalities.  This exposed a bug in `new_from_array`: 'stride' is actually optional under the [official specification ](https://numpy.org/doc/stable/reference/arrays.interface.html).   I was also needlessly relying on pytorch's `.asarray`, when `.from_numpy` would've sufficed.
Would you mind testing these with your alternate configurations to see that the test failures you noted are fixed?

Fixed new_from_array, fixed test for older pytorch

---

doc/intro.rst
examples/pil-numpy-pyvips.py

Here's an update to intro.rst and to the  numpy/PIL example to reflect the new interconversion functionality.
Aside: Interestingly, when I run the updated example, which has some timing code left over from before, I see that PIL is quite a bit faster than pyvips for loading the images I tried:
```shell
examples$ python pil-numpy-pyvips.py ../tests/images/sample.jpg deleteme.jpg
Pillow Time: 0.018997669219970703
pil shape (768, 1024, 3)
Vips Time: 0.025973081588745117
vips shape (768, 1024, 3)
Average pil/vips difference: 0.0
examples$ python pil-numpy-pyvips.py /fast/demo.tif deleteme.tif
Pillow Time: 0.30741429328918457
pil shape (7384, 3192, 3)
Vips Time: 1.0770337581634521
vips shape (7384, 3192, 3)
Average pil/vips difference: 0.0
```
Is this what you expect?

Update for numpy/PIL: intro docs and example

---

pyvips/vimage.py

There is a small typo in pyvips/vimage.py.
Should read `between` rather than `betweeen`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, betweeen -> between

---

pyvips/base.py
pyvips/vdecls.py

Removing these functions ensures that libvips does not fall-back to ABI mode at runtime when building with the deprecated components disabled (`-Ddeprecated=false`), see:
https://github.com/libvips/libvips/issues/2947
These functions were only used by libvips' test suite, which are marked as `@pytest.mark.xfail`, so it's safe to remove.

Remove deprecated symbols

---

doc/intro.rst

A fix for this rendering glitch:

Fix markup glitch

---

examples/gen-enums.py
pyvips/enums.py
pyvips/gvalue.py
pyvips/vdecls.py
pyvips/vimage.py

See the individual commits for more details.

Improve support for `GFlags` types

---

pyvips/__init__.py

See: #443
Tested on Linux using this Dockerfile:
<details>
<summary>Details</summary>
```dockerfile
FROM python:3.12-slim-bookworm
LABEL maintainer="Kleis Auke Wolthuizen <info@kleisauke.nl>"
ARG VIPS_VERSION=8.15.0
WORKDIR /opt/libvips
RUN apt-get update -q \
&& apt-get install -qy --no-install-recommends \
ca-certificates \
curl \
git \
&& curl -Ls https://github.com/kleisauke/libvips-packaging/releases/download/v$VIPS_VERSION/libvips-$VIPS_VERSION-linux-x64.tar.gz | tar -xzC .
WORKDIR /app
ENV LD_LIBRARY_PATH=/opt/libvips/lib
RUN pip install --user git+https://github.com/kleisauke/pyvips.git@single-shared-vips-compat \
&& pip show pyvips
CMD ["python"]
```
</details>
And on Windows by using the `-static` (not `static-ffi`) binaries from: …

Ensure compatibility with a single shared libvips library

---

pyvips/gvalue.py
pyvips/pyvips_build.py
pyvips/vdecls.py

Resolves: #459.
_Split out from #445._

Fix `-Wincompatible-function-pointer-types` warning on Clang

---

pyvips/vdecls.py

Define a couple of declarations as opaque

---

pyvips/vimage.py

<details>
<summary>Details</summary>
```
Direct leak of 50 byte(s) in 10 object(s) allocated from:
#0 0x7f56304f87a3 in malloc (/usr/lib/llvm-18/lib/clang/18/lib/linux/libclang_rt.asan-x86_64.so+0xf87a3) (BuildId: bf9e3747052c46cd49f7974555b1700dce30b8c0)
#1 0x7f562a4b6af9 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x62af9) (BuildId: 9753724b85d60f97b5d5663181ef7f4e69a62131)
#2 0x7f562a4cc4c8 in g_strdup (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x784c8) (BuildId: 9753724b85d60f97b5d5663181ef7f4e69a62131)
#3 0x7f562b3a9911 in g_strdup_inline /usr/include/glib-2.0/glib/gstrfuncs.h:321:10
#4 0x7f562b3a9911 in vips_filename_get_filename /home/runner/work/libvips/libvips/build/../libvips/iofuncs/image.c:1824:9
#5 0x7f562e5526ce in _cffi_f_vips_filename_get_filename …
```

Fix a small memleak in `write_to_buffer()`

---

README.rst
pyproject.toml
pyvips/__init__.py
pyvips/error.py
pyvips/gobject.py
pyvips/gvalue.py
pyvips/pyvips_build.py
pyvips/vconnection.py
pyvips/version.py
pyvips/vimage.py
pyvips/vinterpolate.py
pyvips/vobject.py
pyvips/voperation.py
pyvips/vregion.py
pyvips/vsource.py
pyvips/vsourcecustom.py
pyvips/vtarget.py
pyvips/vtargetcustom.py
setup.cfg
setup.py
tests/helpers/helpers.py
tests/test_progress.py
tests/test_saveload.py

See the individual commits for more details.

Drop support for Python 2.7, migrate to `pyproject.toml`

---

pyvips/vdecls.py

We cannot declare `VipsTypeMap2Fn` as opaque as this callback is used by `type_map()`. Instead, restore the `VipsTypeMap2Fn` definition and use an opaque pointer for the second argument of `vips_type_map()`.
<details>
<summary>Details</summary>
```console
$ python3 gen_cpp_binding.py
Traceback (most recent call last):
File "/home/kleisauke/wasm-vips/build/gen_cpp_binding.py", line 295, in <module>
generate_enums_flags('enums.cpp')
File "/home/kleisauke/wasm-vips/build/gen_cpp_binding.py", line 230, in generate_enums_flags
type_map(type_from_name('GEnum'), add_enum)
File "/home/kleisauke/.local/lib/python3.12/site-packages/pyvips/base.py", line 105, in type_map
cb = ffi.callback('VipsTypeMap2Fn', fn)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected a function ctype, got …
```

Fix `type_map()`

---

doc/intro.rst
examples/pil-numpy-pyvips.py
examples/progress.py
examples/soak-test.py
examples/try5.py
pyvips/__init__.py
pyvips/error.py
pyvips/gobject.py
pyvips/gvalue.py
pyvips/pyvips_build.py
pyvips/vdecls.py
pyvips/vimage.py
pyvips/vinterpolate.py
pyvips/voperation.py
pyvips/vsource.py
pyvips/vtarget.py
setup.py
tests/helpers/helpers.py

Eliminate all old-style string replacement (`%` substitutions) and explicit `.format()` calls, in favor of equivalent f-strings.

Replace all %-substitution and .format() calls with f-strings

---

CHANGELOG.rst
pyvips/__init__.py

Context:
> pyvips could maybe use something similar, I think at the moment it'll try to load glib as a test for semistatic, but that could break on windows if the user has glib from another project on their PATH. Seeing if we can get `g_free` or whatever from libvips ought to be safer.
> _Originally posted by @jcupitt in https://github.com/libvips/ruby-vips/issues/390#issuecomment-1977107148_

Revise logic for unified (semistatic) libvips binaries

---

pyvips/vdecls.py

Handy for the leak checker - simply set `VIPS_LEAK=1`, run your program, and call:
```python
pyvips.vips_lib.vips_shutdown()
```
at the end.
An alternative might be to mark `vips_shutdown()` as destructor, see e.g. commit  https://github.com/kleisauke/libvips/commit/f75675fc4e9de0502a12b2a9aa10f643a2b1146b. However, I'm not sure if that  would cause any side effects (just like with `atexit()` in the past).

Add a declaration for `vips_shutdown()`

---

README.rst
pyvips/__init__.py
pyvips/base.py
pyvips/error.py
pyvips/vdecls.py
pyvips/voperation.py

See the individual commits for more details.

Minor fixes and improvements

---

pyproject.toml

It was likely added in preparation for the pre-built binary wheels, now provided by pyvips-binary. Discovered while reviewing https://github.com/kleisauke/pyvips-binary/commit/7d39fb0e8c8e97f727bcffa7832b24598f8d0af0.

Remove redundant build dependency on wheel

---

README.rst

Noticed this after I wrote comment https://github.com/libvips/pyvips/pull/507#issuecomment-2724645016. However, this is not an issue for [editable installs](https://pip.pypa.io/en/stable/topics/local-project-installs/#editable-installs). For example, this is all fine:
```console
$ pip uninstall -y pyvips pyvips-binary
$ pip cache purge
$ pip install -e .[binary]
$ ldd $(python -m site --user-site)/_libvips.abi3.so | grep libvips
libvips-65e2e1b0.so.42 => /home/kleisauke/.local/lib/python3.13/site-packages/pyvips_binary.libs/libvips-65e2e1b0.so.42 (0x00007f1d86c00000)
```
```console
$ pip uninstall -y pyvips pyvips-binary
$ pip cache purge
$ pip install pyvips-binary
$ pip install -e .
$ ldd $(python -m site --user-site)/_libvips.abi3.so | grep libvips
libvips-65e2e1b0.so.42 => …
```

Simplify install notes

---

.github/workflows/ci.yml

See:
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners
and the failures in PR #537.

CI: run `apt-get update` before installing libvips

---

examples/gen-enums.py
pyvips/enums.py

Inline with commit https://github.com/libvips/php-vips/commit/2e9280ba6e7dcc3c70c8ec007c35075215b71f46.

Remove internal DemandStyle enum

---

pyvips/__init__.py

We are using glib from conan https://conan.io/center/recipes/glib?version=2.85.3
and dlls are named `glib-2.0-0.dll` instead of `libglib-2.0-0.dll` 
Added this change to support both cases

fix glib prefix on windows
